djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("siteapp.urls")),
    # path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siteapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name ="site"

urlpatterns = [
    path("", views.home, name="home"),
    path("<slug:slug>/<int:pk>/", views.PostDetail.as_view(), name="post_detail"),
    path("contact/", views.contact, name="contact"),
    
    path("accounts/signup/", views.SignUpView.as_view(), name="signup"),
    
    path(
        "accounts/login/", 
        auth_views.LoginView.as_view(template_name="siteapp/registration/login.html"),
        name="login"
    ),
    
    path("accounts/logout", auth_views.LogoutView.as_view(), name="logout"),
     
]

siteapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(verbose_name="Post title", max_length=255)
    slug = models.SlugField(verbose_name="Post slug")
    image = models.ImageField(upload_to="upload/siteapp/%Y")
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_commented = models.ForeignKey(Post,verbose_name="Post commented", 
                                       on_delete=models.CASCADE)
    body_comment = models.TextField(verbose_name="Your comment")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return str(self.author)
    

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    
    def __str__(self):
        return self.name
    
    
    

siteapp/forms.py
from django import forms
from django.contrib.auth.models import User

from siteapp.models import Comment, Contact

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ["body_comment"]
        widgets = {
            'body_comment': forms.Textarea(attrs={'cols': 5, 'rows': 5}),
        }
       

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'


    

siteapp/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin, CreateView
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import CommentForm, ContactForm
from .models import Post, Comment

def home(request):
    """ Home page of blog this veiw show the 3 last post """
    
    post_list = Post.objects.order_by("-created_at")
    page = request.GET.get("page", 1)
    
    paginator = Paginator(post_list, 3)
    try: 
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
        
    context = {
        'posts': posts
    }
    return render(request, "siteapp/home.html", context)


class PostDetail(FormMixin, DetailView):
    """ Show post detail with generic view 
    """
    template_name = "siteapp/post_detail.html"
    model = Post
    form_class = CommentForm
    
    def get_success_url(self):
        return reverse("site:post_detail", 
                       kwargs={
                           "slug":self.object.slug ,
                           "pk":self.object.id
                        }
                    )
    
    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        #commentForm in context
        context["form"] = CommentForm(initial={'post':self.object})
        context["comments"] = Comment.objects.filter(post_commented=self.object.id)
        
        return context
    
    
    def post(self, request, *args, **kwargs):
        #when user submit a comment
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
    def form_valid(self, form):
        new_comment = form.save(commit=False)
        new_comment.author = self.request.user
        new_comment.post_commented_id = self.object.id
        new_comment.save()
        
        return super(PostDetail, self).form_valid(form)
    

class SignUpView(CreateView):
    """Class of creation user """
    template_name = "siteapp/registration/signup.html"
    form_class = UserCreationForm
    success_url = reverse_lazy("site:home")
    
    
    def form_valid(self, form):
        valid =super().form_valid(form)
        login(self.request, self.object)
        return valid
    


def contact(request):
    """ Contact view who show contact page """
    form = ContactForm()
    if request.method == "POST" and request.is_ajax():
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            form.save()
            return JsonResponse({"name":name}, status=200)
        else:
            errors = form.errors.as_json()
            return JsonResponse({"errors": errors}, status=200)
    return render(request, 'siteapp/contact.html', {"form":form})

siteapp/templates/siteapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'siteapp/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'siteapp/css/style.css' %}">
    <script src="{% static "siteapp/js/jquery-3.2.1.min.js" %}"></script>
    <title>Blog of technologies</title>
</head>
<body>
    {% include "./layouts/header.html" %}
    
    {% block content %}{% endblock content %}

    <script src="{% static 'siteapp/js/bootstrap.min.js' %}"></script>
</body>
</html>

siteapp/templates/siteapp/contact.html
{% extends './base.html'  %}
{% load crispy_forms_tags %}
{% block content %}
   {% include "./layouts/slider.html" with title="adonsijules@gmail.com" %}
   <div class="container mt-5  mb-5">
   <div class="row ">
      <div class="col-lg-6 col-md-6 m-auto col-sm-12">
         <h3>Contact me </h3>
         <form  method="POST" id="contactForm">
         <div class="message-success"></div>
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" name="contact-submit" class="btn btn-outline btn-sm btn-primary">
         </form>
         
      </div>
   </div>
  
   </div>

   {% block javascript %}
      <script>
         $(document).ready(function() {
            // catch the form's submit event 
            $('#contactForm').submit(function() {
               $.ajax({
                  data: $(this).serialize(),
                  type: $(this).attr("method"),
                  url : {% url 'site:contact' %},
                  success: function(response){
                     $(".message-success").append(`
                        <div class="alert p-3 alert-success">
                        Thank you ${response.name}</div>`
                     )
                     $("#contactForm")[0].reset()
                  }, 
                  error: function(error) {
                     console.log(response.responseJSON.errors)
                  }
                  
               })
               return false;
            });
         })
      </script>
   {% endblock javascript %}

{% endblock content %}

siteapp/templates/siteapp/home.html
{% extends './base.html'  %}
{% load static %}
{% block content %}
   {% include "./layouts/slider.html" with title="Welcome to my Developper blog" %}
    <main class="main container">
        <div class="_last_post mt-3">
            <h4>Last posts</h4>
        </div>
        <section class="container mt-3">
            <div class="row justify-content-between">
                {% for post in posts %}
                    <div class="col-lg-4 col-md-4 col-sm-12 mb-3">
                        <article class="card" >
                            <img class="card-img-top" src="{{post.image.url}}" alt="{{post.slug}}">
                            <div class="card-body">
                                <a href="{% url 'site:post_detail' post.slug post.id %}"> 
                                    <h6> {{ post.title }}</h6>
                                </a>
                                <p class="small"> {{ post.created_at|date:"SHORT_DATE_FORMAT" }}  | Author:  {{ post.author }} </p>
                                <p class="card-text">
                                    {{ post.content|truncatewords:20 }}
                                </p>
                                <a href="{% url 'site:post_detail' post.slug post.id %}" class="btn btn-outline-primary">Read more</a>
                            </div>
                        </article>
                    </div>
                {% endfor %}
            </div>
            {% if posts.has_other_pages %}
                <nav class="Page navigation example">
                    <ul class="pagination">
                        {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link" aria-label="Previous" href="?page={{ posts.previous_page_number }}">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">1</a>
                        </li>
                        {% endif %}
                        {% for i in posts.paginator.page_range %}
                        {% if posts.number == i %}
                            <li class=" page-item active">
                                <a href="" class="page-link">
                                    <span>{{ i }} 
                                    <span class="sr-only">(current)</span></span>
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ i }}">
                                    {{ i }}
                                </a>
                            </li>
                        {% endif %}
                        {% endfor %}
                        {% if posts.has_next %}
                        <li>
                            <a class="page-link" href="?page={{ posts.next_page_number }}">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a href="#" class="page-link">
                            <span>&raquo;</span>
                            </a> 
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                
            {% endif %}
        </section>
    </main>
{% endblock content %}

siteapp/templates/siteapp/layouts/header.html
<header class="navbar navbar-expand-lg navbar-light bg-light">
    <nav class="container">
        <a class="navbar-brand" href="/">BlogTech</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" 
                data-target="#navbarSupportedContent" 
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
        >
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse row justify-content-around" id="navbarSupportedContent">
            <div class="col-lg-8">
                <ul class="navbar-nav float-center">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home <span class="sr-only">(Current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a  class="nav-link" href="{% url 'site:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-4 ">
                {% if user.is_authenticated %}
                <ul class="navbar-nav float-right">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'site:logout' %}">Logout</a>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav float-right">
                    <li class="nav-item">
                        <a  class="nav-link" href="{% url 'site:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a  class="nav-link" href="{% url 'site:signup' %}">Register</a>
                    </li>
                </ul>
                {% endif %}
                
            </div>
            
        </div>
    </nav>
</header>

siteapp/templates/siteapp/layouts/slider.html
 <section class="slider-section">
        <div class="d-flex justify-content-center">
            <div class="block-content-slider-title">
                <h1 class="text-white"> {{ title }} </h1>
            </div>
        </div>
    </section>

siteapp/templates/siteapp/post_detail.html
{% extends './base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="mt-0" style="
    background-image: url({{ post.image.url }}); 
    height: 300px; 
    background-position: center;
    background-size: cover;">
    </section>
    <section class="article-content container mt-4">
        <div class="article-info d-flex justify-content-start">
            <div class="d-flex justify-content-start">
                <div class="image mr-3">
                    <a href="">
                        <img class="rounded-circle" src="https://cdn.pixabay.com/photo/2020/10/01/15/18/tiger-5618802_960_720.jpg" alt="" width="50px" height="50px">
                    </a>
                </div>
                <div>
                    <p class="mb-0">  {{ post.author }} </p>
                    <p class="mb-0"> {{ post.created_at|date:"SHORT_DATE_FORMAT" }} </p>
                </div>
            </div>

        </div>
        <div class="articel-info mt-3">
            <div class="">
                <h1> {{ post.title }} </h1>
            </div>

            <div>
                {{ post.content }}
            </div>
        </div>
    </section>

    <section class='container  comment-block mt-5'>
        <p class='text-uppercase border-bottom pb-2 font-weight-bold'> {{ comments|length }} Comments</p>
        {% if comments|length > 0  %}
            {% for comment in comments %}
                <div class="mb-5 ml-5 card p-1">
                    <div class="d-flex justify-content-start">
                            <div class="image mr-3">
                                <a href="">
                                    <img class="rounded-circle" src="https://cdn.pixabay.com/photo/2020/10/01/15/18/tiger-5618802_960_720.jpg" alt="" width="50px" height="50px">
                                </a>
                            </div>
                            <div class="border-right pr-2">
                                <p class="mb-0">  {{ comment.author }} </p>
                                <p class="mb-0"> {{ comment.created_at|date:"SHORT_DATE_FORMAT" }} </p>
                            </div>
                            <div class="pl-2">
                                {{ comment.body_comment }}
                            </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="alert alert-info">
                Zero comment, Be first to comment this post
            </div>
        {% endif %}
       
        <p class='text-uppercase border-bottom pb-2 font-weight-bold'>Add comment</p>
        <form action="" method="post" id="commentform">
            {% csrf_token %}
            <div class="form-group">
                {{ form|crispy }}
            </div> 
            <div class="form-group">
                <button type="submit" {% firstof user.is_authenticated "disabled" %}  class=" btn btn-outline-primary">Comment</button>
                {% if user.is_authenticated == False %}
                    <small class="ml-5 text-info"> 
                    The form is disabled you must connected before comment post  
                    <a href="{% url 'site:login' %}?next={{ request.path }}#commentform">Log In here</a> 
                    </small>
                {% endif %}
            </div>
        </form>
    </section>
   
{% endblock content %}